service: serverlessapi
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello

    provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}

  deploymentBucket:
    name: ${ssm:account_code_bucket_name}
    serverSideEncryption: AES256

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-east-1:435971970349:table/hack-a-pg-table

package:
  excludeDevDependencies: True
  exclude:
    - package.json
    - package-lock.json
    - node_modules/**
    - tests/**
  include:
    - ../shared/**
    - ../__init__.py-


plugins:
  - serverless-python-requirements