service: serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}

  deploymentBucket:
      name: ${ssm:account_code_bucket_name}
      serverSideEncryption: AES256

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-east-1:114660185804:table/book-list-app-table

package:
  excludeDevDependencies: True
  exclude:
    - package.json
    - package-lock.json
    - node_modules/**
    - tests/**
  include:
    - ../shared/**
    - ../__init__.py-

functions:    
  test-books:
    handler: test-books.test
    events:
      - http:
          path: /test-books
          method: get
          cors:
            origins:
                - "*"
            allowCredentials: true
  
  get-books:
    handler: get-books.handler
    events:
      - http:
          path: /get-books
          method: get
          cors:
            origins:
                - "*"
            allowCredentials: true