name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-20.04
    outputs:
      terraform: ${{ steps.filter.outputs.terraform }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          base: main
          filters: |
            terraform:
              - 'Terraform/**'

  terraform:
    needs: changes
        if: ${{ needs.changes.outputs.terraform == 'true' }}
        runs-on: ubuntu-20.04
        name: "Terraform"
        steps:
          - uses: fusion-engineering/setup-git-credentials@v2
            with:
                credentials: https://${{secrets.INNERSOURCE_READ_USER}}:${{secrets.INNERSOURCE_READ_PAT}}@github.com/
          - uses: actions/checkout@main
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
              aws-region: us-east-1
          - uses: hashicorp/setup-terraform@v1
            with:
              terraform_version: 1.1.7
          - name: Terraform fmt
            id: fmt
            run: terraform fmt

          - name: "Terraform Init"
            id: init
            run: |
              terraform init
            working-directory: Terraform
            env:
              TF_WORKSPACE: "prod"

          - name: "Terraform Apply"
            id: apply
            run: terraform apply -auto-approve
            working-directory: Terraform
            env:
              TF_WORKSPACE: "prod"